-- 코드를 입력하세요
SELECT PRO.PRODUCT_CODE, SUM(OFF.SALES_AMOUNT)*PRO.PRICE AS SALES
FROM PRODUCT PRO
JOIN OFFLINE_SALE OFF
ON PRO.PRODUCT_ID = OFF.PRODUCT_ID
GROUP BY PRO.PRODUCT_CODE
ORDER BY SALES DESC, PRO.PRODUCT_CODE ASC;